/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Days */
        get: operations["days_api_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Windows */
        get: operations["windows_api_windows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spots
         * @description The log screen's only data source, and it carries no scores.
         *
         *     This is the architectural half of "ask before revealing": there is no number in this
         *     response to leak, so hiding it is not left to a component.
         */
        get: operations["spots_api_spots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots/{spot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spot Day */
        get: operations["spot_day_api_spots__spot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Observation
         * @description Store one label, then reveal what we had said.
         *
         *     The order is the point. Nothing in the request tells the client our score, and the
         *     reveal only exists in this response — by which time the rating is already stored and
         *     cannot be influenced by it.
         */
        post: operations["create_observation_api_observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enter */
        get: operations["enter_enter_get"];
        put?: never;
        /** Submit Key */
        post: operations["submit_key_enter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest.webmanifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manifest
         * @description Enough for "Add to Home Screen" to behave like an app.
         */
        get: operations["manifest_manifest_webmanifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_submit_key_enter_post */
        Body_submit_key_enter_post: {
            /** Key */
            key: string;
        };
        /** DaysOut */
        DaysOut: {
            /** Timezone */
            timezone: string;
            /**
             * Default
             * Format: date
             */
            default: string;
            /** Days */
            days: string[];
            /** As Of */
            as_of?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourOut */
        HourOut: {
            /**
             * Valid At
             * Format: date-time
             */
            valid_at: string;
            /** At Local */
            at_local: string;
            /** Score */
            score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "no" | "maybe" | "go";
            /** Reasons */
            reasons: components["schemas"]["ReasonOut"][];
        };
        /**
         * ObservationIn
         * @description One session, in the local terms a person types them in.
         */
        ObservationIn: {
            /** Spot Id */
            spot_id: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /**
             * Start
             * @description Local HH:MM
             */
            start: string;
            /**
             * End
             * @description Local HH:MM
             */
            end: string;
            /**
             * Kind
             * @default surfed
             * @enum {string}
             */
            kind: "surfed" | "checked" | "cam";
            /**
             * Rating
             * @description Absolute quality, answered blind
             */
            rating: number;
            /** Would Return */
            would_return?: boolean | null;
            /** Crowd */
            crowd?: ("empty" | "ok" | "busy" | "zoo") | null;
            /** Faults */
            faults?: ("swell_dir" | "size" | "period" | "wind" | "tide")[];
            /** Note */
            note?: string | null;
        };
        /** ObservationOut */
        ObservationOut: {
            /** Spot Name */
            spot_name: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Span */
            span: string;
            /** Rating */
            rating: number;
            /** Duplicate */
            duplicate: boolean;
            shown?: components["schemas"]["ShownOut"] | null;
        };
        /** ReasonOut */
        ReasonOut: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Points */
            points: number;
        };
        /**
         * ShownOut
         * @description What we had said. Only ever returned *after* a label is stored.
         */
        ShownOut: {
            /** Score */
            score: number;
            /** Verdict */
            verdict: string;
            /** Score Version */
            score_version: string;
            /** Spec Version */
            spec_version: string;
        };
        /** SpotDayOut */
        SpotDayOut: {
            spot: components["schemas"]["SpotDetailOut"];
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Hours */
            hours: components["schemas"]["HourOut"][];
        };
        /** SpotDetailOut */
        SpotDetailOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Region
             * @enum {string}
             */
            region: "ericeira" | "lisbon" | "peniche";
            /** Swell From Min */
            swell_from_min: number;
            /** Swell From Max */
            swell_from_max: number;
            /** Size Min M */
            size_min_m: number;
            /** Size Max M */
            size_max_m: number;
            /** Period Min S */
            period_min_s: number;
            /** Offshore From */
            offshore_from: number;
            /** Max Onshore Kn */
            max_onshore_kn: number;
            /** Tides */
            tides: ("low" | "mid" | "high")[];
        };
        /**
         * SpotOut
         * @description Deliberately score-free.
         *
         *     This is the whole payload the log screen is allowed to fetch. If a score were on
         *     this model, our prediction would be sitting on the device while someone decides how
         *     their session went, and "we do not show it" would be a promise the component makes
         *     rather than a fact about the response.
         */
        SpotOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Region
             * @enum {string}
             */
            region: "ericeira" | "lisbon" | "peniche";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowOut */
        WindowOut: {
            /** Spot Id */
            spot_id: string;
            /** Spot Name */
            spot_name: string;
            /**
             * Region
             * @enum {string}
             */
            region: "ericeira" | "lisbon" | "peniche";
            /** Spec Version */
            spec_version?: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Starts At Local
             * Format: date-time
             */
            starts_at_local: string;
            /**
             * Ends At Local
             * Format: date-time
             */
            ends_at_local: string;
            /**
             * Peak At
             * Format: date-time
             */
            peak_at: string;
            /**
             * Peak At Local
             * Format: date-time
             */
            peak_at_local: string;
            /** Hours */
            hours: number;
            /** Score */
            score: number;
            /** Peak Score */
            peak_score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "no" | "maybe" | "go";
            /** Vetoed */
            vetoed: boolean;
            /** Reasons */
            reasons: components["schemas"]["ReasonOut"][];
        };
        /** WindowsOut */
        WindowsOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Days */
            days: string[];
            /** Timezone */
            timezone: string;
            /** Score Version */
            score_version: string;
            /** As Of */
            as_of?: string | null;
            /** Windows */
            windows: components["schemas"]["WindowOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    days_api_days_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaysOut"];
                };
            };
        };
    };
    windows_api_windows_get: {
        parameters: {
            query?: {
                /** @description Local (Europe/Lisbon) day. Defaults to the next day with surfable hours. */
                day?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindowsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spots_api_spots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotOut"][];
                };
            };
        };
    };
    spot_day_api_spots__spot_id__get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: never;
            path: {
                spot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotDayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_observation_api_observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enter_enter_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    submit_key_enter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_submit_key_enter_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manifest_manifest_webmanifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
