-- Fixture labels must be separable from real ones, forever.
--
-- `gogo demo` writes plausible sessions so the Stage 2 harness can be built and tested
-- before 100 real labels exist. That is legitimate; an evaluation pipeline cannot be
-- written against an empty table. What is not legitimate is letting those rows count.
--
-- A synthetic label is generated *from our own score*, so any metric computed over it
-- measures our assumptions and returns a flattering number with no way to notice. The
-- frozen decision says a fabricated observation is indistinguishable from a real label
-- once the harness exists — so this column is what makes that statement false.
--
-- A column and not a convention: handles get renamed, notes get edited, and a filter
-- someone forgot to apply is exactly how contamination happens. Every read path used
-- for evaluation defaults to `is_synthetic = false`.

ALTER TABLE observations
    ADD COLUMN is_synthetic boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN observations.is_synthetic IS
    'Generated by gogo demo. Never include in an evaluation number.';

-- Real labels are the common read and will stay the smaller set for a while.
CREATE INDEX observations_real_idx ON observations (spot_id, started_at)
    WHERE NOT is_synthetic;
